pipeline {
  agent any
  options {
    buildDiscarder(logRotator(artifactNumToKeepStr: '10'))
    timestamps()
    disableConcurrentBuilds()
    timeout(time: 2, unit: 'HOURS')
  }

  parameters{
    string(
      defaultValue: '6',
      description: '<em>[Integer]</em> Retention months. Will  keep only jobs less than <code>$retention</code> months old.',
      name: 'retention',
      trim: true
    )
    booleanParam(
      defaultValue: false,
      description: '''dryRun:<ul><li><b>True</b>: Will run in dryRun and only disply</li><li><b>False</b>: Will perform deletion according to <code>$retention</code> value.</li></ul>''',
      name: 'dryRun'
    )
  }

  stages {
    stage('Clean jobs') {
      steps{
        script{
          //get scipt from git
          git branch: 'gen_cleanup', changelog: false, credentialsId: 'jenkins-sdp-urt', poll: false, url: 'https://r11-sfdh-scm-001.devops.in.idemia.com/bitbucket/scm/devops/rt-gen-toolbox.git'
          //load script
          def cleanup = load 'jobCleanup.groovy'
          //check entry
          def userRetention = params.retention
          if (userRetention != null && !userRetention.isEmpty() && userRetention.isInteger()) {
            def integerRetention = userRetention.toInteger()
            //run cleanup
            use(groovy.time.TimeCategory) {
              cleanup.generationFolderCleanUp(integerRetention.month, params.dryRun)
            }
          } else {
            error 'The provided input for retention is either empty, null, or not an integer...'
          }
        }
      }
    }
  }
}
