---
- name: Retrieve informations
  hosts: all
  #connection: local
  gather_facts: true
  tasks:
    #- name: Add host key to known hosts
    #  shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

    - name: Display OS information
      debug:
        msg: "Host {{ inventory_hostname }} has {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display IP address
      debug:
        msg: "Host {{ inventory_hostname }} IP address is {{ ansible_default_ipv4.address }}"

    #- name: Get jenkins instance
    #  ansible.builtin.shell: docker ps -a --format "table {{ '{{' }} .Names {{ '}}' }}" | grep "jenkins" | awk '{printf("%s;",$0)}'
    #  register: jk

    - name: Gather informations
      set_fact:
        host_information: >-
          {{
            host_information | default({}) | combine({
              inventory_hostname: {
                'os': ansible_distribution + ' ' + ansible_distribution_version,
                'ip': ansible_default_ipv4.address
              }
            })
          }}
    - name: Register gathered informations
      add_host:
        name: "DUMMY_HOST"
        host_info: "{{ host_information }}"

#Build report
- name: Generate Reports
  hosts: localhost
  connection: local
  vars:
    template_src: templates
    template_dest: reports
  gather_facts: false
  tasks:
    - name: Set variable
      set_fact:
        host_information: "{{ hostvars['DUMMY_HOST']['host_info'] }}"
    - name: Create CSV report
      template:
        src: '{{ template_src }}/report_csv.j2'
        dest: '{{ template_dest }}/report.csv'
    - name: Create HTML report
      template:
        src: '{{ template_src }}/report_html.j2'
        dest: '{{ template_dest }}/report.html'
