# Run: ansible-playbook -kK playbook-test.yaml -i inventory.yaml
---
# Self-contained ansible playbook
- name: Run jobs and generate simple report
  hosts: all
  gather_facts: yes
  order: sorted

  #collections:
  #  - ansible.builtin
  #  - community.general

  vars:
    ansible_remote_tmp: /tmp
    # Location for job reports
    report_path: reports
    template_path: templates

  # Pre tasks
  pre_tasks:
    - name: Create output folder
      run_once: yes
      delegate_to: localhost
      file:
        path: "{{ report_path }}"
        state: directory

  # Tasks
  tasks:

    # Get running containers
    - name: Run a command and save the results
      become: yes
      command: docker ps --format "{{ '{{' }} .Names {{ '}}' }}"
      register: cmd1_results
      failed_when: "'Failed' in cmd1_results.stderr"

  # Post tasks
  post_tasks:
    - name: Save some useful facts under Ansible controller
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      set_fact:
        date_str: "{{ date }}_{{ hms }}"
        date_str_pretty: "{{ date }} {{ hms_pretty }}"
        success_list: "{{ ansible_play_hosts }}"
        failed_list: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
      vars:
        date: "{{ '%Y-%m-%d' | strftime }}"
        hms_pretty: "{{ '%H:%M:%S' | strftime }}"
        hms: "{{ hms_pretty | replace(':','-') }}"

    # The template module
    - name: Save job report to {{ report_path }}
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      template:
        src: "{{ template_path }}/report_html.j2"
        dest: "{{ report_path }}/report.html"
    - name: Save job report to {{ report_path }}
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      template:
        src: "{{ template_path }}/report_csv.j2"
        dest: "{{ report_path }}/report.csv"
